### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolsource#71]
- [x] fix check_all function in docker folder (see testprotocol repo) and add this to #70
- [x] fix generate_artifact_pr.yml (see testprotocol repo) and add this to #70
- [x] update protocolhelper to 0.4.3 in renv.lock and add this to #70
- [x] mention the use of `git pull origin main` in the contributing guidelines and add this to #70
- [x] update the branch protection rules in settings so that status checks are required after #70 is merged
